# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: ba5ebfc2d07f7b186f2ca601b247b75654f27bfe8a471c2f83439fc45f858fdb12016e463dd48d92d47cf817a16f3e12f65ffb29c885a295d73f786c260c8229

test:
  secret_key_base: 8b7f41dda49efa6a2ea1f762a94398620761d9899c8cc4d4765dec30e5fd9504ef3177c76f18f3a46a3a1f44fbb82d4bba0a78d7a4be6102079f999d0c8a0140

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
